### ISSUE TITLE
Front End Output Use Classes and Not Data Attr

### ISSUE THREAD

**Issue by turtlepod** [turtlepod/fx-builder#39]
Using data attribute, even though we can target it using CSS it's not really understandable to most user. Using CSS Classes is probably better.

This:
```css
.fxb-row[data-layout="12_12"] .fxb-col-1{
	width: 47.5%;
	margin-right: 5%;
}
```
VS This:
```css
.fxb-row.fxb-layout-12_12 .fxb-col-1{
	width: 47.5%;
	margin-right: 5%;
}
```
